### PR TITLE
Move from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by mathomp4**
I missed pFlogger in the Travis -> CircleCI sweep

### CODE REVIEW

**Comment by tclune** [comment]
@mathomp4 Should this be merged in?

**Comment by mathomp4** [comment]
@tclune Does yaFyaml require a specific version of gFTL? 
```
Scanning dependencies of target yafyaml
[  3%] Building Fortran object src/CMakeFiles/yafyaml.dir/KeywordEnforcer.F90.o
[  6%] Building Fortran object src/CMakeFiles/yafyaml.dir/AbstractSchema.F90.o
[  9%] Building Fortran object src/CMakeFiles/yafyaml.dir/AbstractTextStream.F90.o
[ 12%] Building Fortran object src/CMakeFiles/yafyaml.dir/ArrayWrapper.F90.o
[ 16%] Building Fortran object src/CMakeFiles/yafyaml.dir/ErrorCodes.F90.o
[ 19%] Building Fortran object src/CMakeFiles/yafyaml.dir/None.F90.o
[ 22%] Building Fortran object src/CMakeFiles/yafyaml.dir/OrderedStringUnlimitedMap.F90.o
/home/runner/gfe/yaFyaml/src/OrderedStringUnlimitedMap.F90:2:7:

    2 |   use gFTL_StringIntegerMap
      |       1
Fatal Error: Cannot open module file ‘gftl_stringintegermap.mod’ for reading at (1): No such file or directory
compilation terminated.
make[2]: *** [src/CMakeFiles/yafyaml.dir/build.make:82: src/CMakeFiles/yafyaml.dir/OrderedStringUnlimitedMap.F90.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:283: src/CMakeFiles/yafyaml.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
``

**Comment by mathomp4** [comment]
Oh. wait. This might be due to that weird "bug in Cmake" that we talked about a week or two ago. Where it was building the the subrepo gFTL even though gFTL had already been built!

**Comment by mathomp4** [comment]
Hmm. No even if I use that fix by creating a `bugfix/mathomp4/build_submodule_fix` branch in gFTL-shared, yaFyaml, fArgParse, and pFUnit it doesn't help. Indeed, I now die *sooner* than before because gFTL-shared can't build:
```
Scanning dependencies of target gftl-shared
[  1%] Building Fortran object src/CMakeFiles/gftl-shared.dir/Complex128Vector.F90.o
[  2%] Building Fortran object src/CMakeFiles/gftl-shared.dir/Complex32Vector.F90.o
/home/runner/gfe/gFTL-shared/src/Complex32Vector.F90:8:2:

    8 | #undef _vectoriterator
      |  1~~~~~~~~~~~~~~~~~~~~ 
Fatal Error: templates/vector.inc: No such file or directory
/home/runner/gfe/gFTL-shared/src/Complex128Vector.F90:8:2:

    8 | #undef _vectoriterator
      |  1~~~~~~~~~~~~~~~~~~~~ 
Fatal Error: templates/vector.inc: No such file or directory
compilation terminated.
compilation terminated.
```
So I grabbed gFTL and gFTL-shared to try and diagnose locally...and nothing I can do in gFTL-shared seems to help. Because `main` of gFTL is the v1.3.0 code, that means gFTL-shared should use:
```cmake
target_link_libraries (gftl-shared PUBLIC GFTL::gftl)
```
but that doesn't work. So, I manually moved gFTL back to v1.2.7 where:
```cmake
target_link_libraries (gftl-shared PUBLIC gftl)
```
should work. And in the `--trace-expand` output of cmake I see:
```
/Users/mathomp4/TestGFECmakeFix/gFTL-shared/cmake/build_submodule.cmake(10):  find_package(GFTL QUIET )
/Users/mathomp4/GFE/GFTL-1.2/cmake/GFTLConfig-version.cmake(3):  set(PACKAGE_VERSION 1.2.7 )
/Users/mathomp4/GFE/GFTL-1.2/cmake/GFTLConfig-version.cmake(5):  if(PACKAGE_FIND_VERSION_MAJOR EQUAL 0 )
/Users/mathomp4/GFE/GFTL-1.2/cmake/GFTLConfig-version.cmake(6):  set(PACKAGE_VERSION_COMPATIBLE TRUE )
...
/Users/mathomp4/GFE/GFTL-1.2/cmake/GFTL.cmake(55):  set_target_properties(gftl PROPERTIES INTERFACE_INCLUDE_DIRECTORIES /Users/mathomp4/GFE/GFTL-1.2/include )
...
```
So it seems like it should have the `include/` directory of gFTL! And yet:
```console
❯ make install VERBOSE=1
/Users/mathomp4/.homebrew/brew/Cellar/cmake/3.19.1/bin/cmake -S/Users/mathomp4/TestGFECmakeFix/gFTL-shared -B/Users/mathomp4/TestGFECmakeFix/gFTL-shared/build --check-build-system CMakeFiles/Makefile.cmake 0
/Users/mathomp4/.homebrew/brew/Cellar/cmake/3.19.1/bin/cmake -E cmake_progress_start /Users/mathomp4/TestGFECmakeFix/gFTL-shared/build/CMakeFiles /Users/mathomp4/TestGFECmakeFix/gFTL-shared/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/Users/mathomp4/TestGFECmakeFix/gFTL-shared/build'
make  -f src/CMakeFiles/gftl-shared.dir/build.make src/CMakeFiles/gftl-shared.dir/depend
make[2]: Entering directory '/Users/mathomp4/TestGFECmakeFix/gFTL-shared/build'
cd /Users/mathomp4/TestGFECmakeFix/gFTL-shared/build && /Users/mathomp4/.homebrew/brew/Cellar/cmake/3.19.1/bin/cmake -E cmake_depends "Unix Makefiles" /Users/mathomp4/TestGFECmakeFix/gFTL-shared /Users/mathomp4/TestGFECmakeFix/gFTL-shared/src /Users/mathomp4/TestGFECmakeFix/gFTL-shared/build /Users/mathomp4/TestGFECmakeFix/gFTL-shared/build/src /Users/mathomp4/TestGFECmakeFix/gFTL-shared/build/src/CMakeFiles/gftl-shared.dir/DependInfo.cmake --color=
Dependee "/Users/mathomp4/TestGFECmakeFix/gFTL-shared/build/src/CMakeFiles/gftl-shared.dir/DependInfo.cmake" is newer than depender "/Users/mathomp4/TestGFECmakeFix/gFTL-shared/build/src/CMakeFiles/gftl-shared.dir/depend.internal".
Dependee "/Users/mathomp4/TestGFECmakeFix/gFTL-shared/build/src/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/Users/mathomp4/TestGFECmakeFix/gFTL-shared/build/src/CMakeFiles/gftl-shared.dir/depend.internal".
Scanning dependencies of target gftl-shared
make[2]: Leaving directory '/Users/mathomp4/TestGFECmakeFix/gFTL-shared/build'
make  -f src/CMakeFiles/gftl-shared.dir/build.make src/CMakeFiles/gftl-shared.dir/build
make[2]: Entering directory '/Users/mathomp4/TestGFECmakeFix/gFTL-shared/build'
[  1%] Building Fortran object src/CMakeFiles/gftl-shared.dir/Complex128Vector.F90.o
cd /Users/mathomp4/TestGFECmakeFix/gFTL-shared/build/src && /Users/mathomp4/installed/Core/gcc-gfortran/10.2.0/bin/gfortran -D_DOUBLE_DEFAULT_KIND=8 -D_DOUBLE_DEFAULT_KIND_IS_REAL64 -D_GNU -D_INT_DEFAULT_KIND=4 -D_INT_DEFAULT_KIND_IS_INT32 -D_ISO_INT16=2 -D_ISO_INT32=4 -D_ISO_INT64=8 -D_ISO_INT8=1 -D_ISO_REAL128=16 -D_ISO_REAL32=4 -D_ISO_REAL64=8 -D_LOGICAL_DEFAULT_KIND=4 -D_REAL_DEFAULT_KIND=4 -D_REAL_DEFAULT_KIND_IS_REAL32 -I/Users/mathomp4/TestGFECmakeFix/gFTL-shared/build/mod -g -cpp -fbacktrace -ffree-line-length-512 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.15 -J../mod -fPIC -c /Users/mathomp4/TestGFECmakeFix/gFTL-shared/src/Complex128Vector.F90 -o CMakeFiles/gftl-shared.dir/Complex128Vector.F90.o
/Users/mathomp4/TestGFECmakeFix/gFTL-shared/src/Complex128Vector.F90:8:2:

    8 | #undef _vectoriterator
      |  1~~~~~~~~~~~~~~~~~~~~
Fatal Error: templates/vector.inc: No such file or directory
compilation terminated.
make[2]: *** [src/CMakeFiles/gftl-shared.dir/build.make:1005: src/CMakeFiles/gftl-shared.dir/Complex128Vector.F90.o] Error 1
make[2]: Leaving directory '/Users/mathomp4/TestGFECmakeFix/gFTL-shared/build'
make[1]: *** [CMakeFiles/Makefile2:163: src/CMakeFiles/gftl-shared.dir/all] Error 2
make[1]: Leaving directory '/Users/mathomp4/TestGFECmakeFix/gFTL-shared/build'
make: *** [Makefile:149: all] Error 2
```

**Comment by mathomp4** [comment]
Closing as #47 has these fixes in it.

**Pull request closed without merging**
